# Generated by Django 3.2.4 on 2021-10-04 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talkmodel',
            name='talk_time',
            field=models.TimeField(),
        ),
    ]
