# Generated by Django 3.2.4 on 2021-10-04 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_talkmodel_talk_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talkmodel',
            name='talk_time',
            field=models.TimeField(null=True),
        ),
    ]
