# Generated by Django 3.2.4 on 2021-10-04 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_talkmodel_talk_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberModal',
            fields=[
                ('member_type', models.CharField(choices=[('Speaker', 'Speaker'), ('Participant', 'Participant')], max_length=25)),
                ('member_name', models.CharField(max_length=25)),
                ('member_email', models.EmailField(max_length=100, primary_key=True, serialize=False)),
                ('member_talk_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.talkmodel')),
            ],
        ),
        migrations.RemoveField(
            model_name='speakermodal',
            name='speaker_talk_title',
        ),
        migrations.DeleteModel(
            name='ParticipantModel',
        ),
        migrations.DeleteModel(
            name='SpeakerModal',
        ),
    ]
