# Generated by Django 3.2.4 on 2021-10-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20211005_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membermodal',
            name='member_email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='membermodal',
            name='member_name',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
