# Generated by Django 3.2.4 on 2021-10-05 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20211005_1425'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MemberModal',
            new_name='MemberModel',
        ),
    ]
