# Generated by Django 5.0.4 on 2024-04-18 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_membermodal_membermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='talkmodel',
            name='projector_number',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='talkmodel',
            name='room_number',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='talkmodel',
            name='talk_duration',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
